SQL_UP = u"""
ALTER TABLE `wp_rg_form_view` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_menus` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_projectapplications` ENGINE = InnoDB;
ALTER TABLE `wp_rg_lead_meta` ENGINE = InnoDB;
ALTER TABLE `wp_ecpt_taxonomies` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_phonetype` ENGINE = InnoDB;
ALTER TABLE `wp_rg_lead_notes` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_pages` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_members` ENGINE = InnoDB;
ALTER TABLE `wp_rg_lead_detail` ENGINE = InnoDB;
ALTER TABLE `wp_signups` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_membergroup` ENGINE = InnoDB;
ALTER TABLE `wp_term_relationships` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_groups` ENGINE = InnoDB;
ALTER TABLE `wp_term_taxonomy` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_group` ENGINE = InnoDB;
ALTER TABLE `wp_rg_lead_detail_long` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_projects` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_ethnicity` ENGINE = InnoDB;
ALTER TABLE `wp_rg_form` ENGINE = InnoDB;
ALTER TABLE `wp_posts` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_union` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_twilio_numbers` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_tickets` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_sms_log_old` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_sms_log` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_roles` ENGINE = InnoDB;
ALTER TABLE `wp_rg_lead` ENGINE = InnoDB;
ALTER TABLE `wp_rg_form_meta` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_relationtypes` ENGINE = InnoDB;
ALTER TABLE `wp_gf_addon_feed` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_relations` ENGINE = InnoDB;
ALTER TABLE `wp_rg_incomplete_submissions` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_projecttype` ENGINE = InnoDB;
ALTER TABLE `wp_termmeta` ENGINE = InnoDB;
ALTER TABLE `wp_terms` ENGINE = InnoDB;
ALTER TABLE `wp_postmeta` ENGINE = InnoDB;
ALTER TABLE `wp_mail_bank_meta` ENGINE = InnoDB;
ALTER TABLE `wp_commentmeta` ENGINE = InnoDB;
ALTER TABLE `wp_yoast_seo_meta` ENGINE = InnoDB;
ALTER TABLE `wp_yoast_seo_links` ENGINE = InnoDB;
ALTER TABLE `wp_comments` ENGINE = InnoDB;
ALTER TABLE `wp_links` ENGINE = InnoDB;
ALTER TABLE `wp_mail_bank` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_citylivein` ENGINE = InnoDB;
ALTER TABLE `wp_ecpt_meta_box_fields` ENGINE = InnoDB;
ALTER TABLE `wp_mail_bank_logs` ENGINE = InnoDB;
ALTER TABLE `wp_options` ENGINE = InnoDB;
ALTER TABLE `wp_ecpt_meta_boxes` ENGINE = InnoDB;
ALTER TABLE `wp_usermeta` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_admin` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_bulkemails_members` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_admin_old` ENGINE = InnoDB;
ALTER TABLE `wp_ecpt_post_types` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_age` ENGINE = InnoDB;
ALTER TABLE `wp_users` ENGINE = InnoDB;
ALTER TABLE `wp_ontrix_bulkemails_email` ENGINE = InnoDB;
ALTER TABLE `wp_mail_bank_meta` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_gf_entry_notes` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_gf_draft_submissions` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_gf_entry` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_gf_entry_meta` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_hfcm_scripts` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_gf_form` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_gf_form_meta` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_gf_form_view` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_mail_bank_logs` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_hustle_modules` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_hustle_modules_meta` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_links` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_mail_bank` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_mail_bank_email_logs` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `states` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `clients` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_options` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_wflocs` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_wfconfig` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_wfcrawlers` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_wffilechanges` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_wffilemods` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_wfhits` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_wfhoover` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_wfissues` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_wfknownfilelist` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_wflivetraffichuman` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_wflogins` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_wfblockediplog` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_wfls_2fa_secrets` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_wfls_settings` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_wfnotifications` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_wfpendingissues` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_wfreversecache` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_wfsnipcache` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_wfstatus` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_wftrafficrates` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_yoast_seo_links` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_wfblocks7` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_users` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_postmeta` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_rg_lead` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_posts` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_redirection_404` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_redirection_groups` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_redirection_items` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_redirection_logs` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_rg_form` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_rg_form_meta` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_rg_form_view` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_rg_incomplete_submissions` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_rg_lead_detail` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_usermeta` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_rg_lead_detail_long` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_rg_lead_meta` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_rg_lead_notes` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_sgpb_subscribers` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_sgpb_subscription_error_log` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_signups` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_term_relationships` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_term_taxonomy` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_termmeta` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_terms` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_gf_addon_feed` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_yoast_seo_meta` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_esign_users` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_esign_documents_meta` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_esign_settings` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_ecpt_meta_boxes` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_ecpt_post_types` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_esign_invitations` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_esign_documents_stand_alone_docs` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_em_theme_metas` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_esign_documents_signatures` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_esign_documents_fields_data` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_esign_signatures` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_ecpt_taxonomies` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_esign_documents_events` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_em_modal_metas` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_esign_documents` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_esign_document_users` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_em_themes` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_em_modals` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_ecpt_meta_box_fields` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_esign_documents_signer_field_data` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_comments` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_commentmeta` DEFAULT COLLATE latin1_swedish_ci;
ALTER TABLE `wp_rg_lead` CHANGE `user_agent` `user_agent` varchar(250) NOT NULL DEFAULT '';
ALTER TABLE `wp_ecpt_taxonomies` CHANGE `show_tagcloud` `show_tagcloud` int(4) NOT NULL;
ALTER TABLE `wp_ecpt_taxonomies` CHANGE `show_in_nav_menus` `show_in_nav_menus` int(4) NOT NULL;
ALTER TABLE `wp_rg_lead` CHANGE `status` `status` varchar(20) NOT NULL DEFAULT 'active';
ALTER TABLE `wp_rg_lead` CHANGE `transaction_id` `transaction_id` varchar(50) DEFAULT NULL;
ALTER TABLE `wp_rg_lead` CHANGE `payment_method` `payment_method` varchar(30) DEFAULT NULL;
ALTER TABLE `wp_rg_lead` CHANGE `payment_status` `payment_status` varchar(15) DEFAULT NULL;
ALTER TABLE `wp_rg_lead` CHANGE `currency` `currency` varchar(5) DEFAULT NULL;
ALTER TABLE `wp_wfnotifications` CHANGE `new` `new` int(3) unsigned NOT NULL DEFAULT '1';
ALTER TABLE `wp_rg_lead_detail` CHANGE `form_id` `form_id` int(8) unsigned NOT NULL;
ALTER TABLE `wp_rg_lead` CHANGE `source_url` `source_url` varchar(200) NOT NULL DEFAULT '';
ALTER TABLE `wp_rg_lead` CHANGE `ip` `ip` varchar(39) NOT NULL;
ALTER TABLE `wp_rg_lead` CHANGE `form_id` `form_id` int(8) unsigned NOT NULL;
ALTER TABLE `wp_ecpt_taxonomies` CHANGE `with_front` `with_front` int(4) NOT NULL;
ALTER TABLE `wp_ecpt_taxonomies` CHANGE `enable_filter` `enable_filter` int(4) NOT NULL;
ALTER TABLE `wp_rg_incomplete_submissions` CHANGE `submission` `submission` longtext NOT NULL;
ALTER TABLE `wp_rg_incomplete_submissions` CHANGE `source_url` `source_url` longtext NOT NULL;
ALTER TABLE `wp_rg_incomplete_submissions` CHANGE `ip` `ip` varchar(39) NOT NULL;
ALTER TABLE `wp_wftrafficrates` CHANGE `hitType` `hitType` varchar(255) NOT NULL DEFAULT 'hit';
ALTER TABLE `wp_ecpt_taxonomies` CHANGE `hierarchical` `hierarchical` int(4) NOT NULL;
ALTER TABLE `wp_rg_lead_detail` CHANGE `value` `value` longtext;
ALTER TABLE `wp_ecpt_post_types` CHANGE `with_front` `with_front` int(4) NOT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `page_attributes` `page_attributes` int(4) NOT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `show_in_nav_menus` `show_in_nav_menus` int(4) NOT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `menu_position` `menu_position` int(4) NOT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `exclude_from_search` `exclude_from_search` int(4) NOT NULL;
ALTER TABLE `wp_rg_lead_notes` CHANGE `note_type` `note_type` varchar(50) DEFAULT NULL;
ALTER TABLE `wp_rg_lead_notes` CHANGE `value` `value` longtext;
ALTER TABLE `wp_rg_lead_notes` CHANGE `user_name` `user_name` varchar(250) DEFAULT NULL;
ALTER TABLE `wp_wfstatus` CHANGE `level` `level` int(3) unsigned NOT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `post_tags` `post_tags` int(4) NOT NULL;
ALTER TABLE `wp_rg_incomplete_submissions` CHANGE `email` `email` varchar(255) DEFAULT NULL;
ALTER TABLE `wp_rg_lead_meta` CHANGE `meta_value` `meta_value` longtext;
ALTER TABLE `wp_rg_lead_meta` CHANGE `meta_key` `meta_key` varchar(255) DEFAULT NULL;
ALTER TABLE `wp_rg_lead_meta` CHANGE `form_id` `form_id` int(8) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `wp_ecpt_post_types` CHANGE `categories` `categories` int(4) NOT NULL;
ALTER TABLE `wp_wfstatus` CHANGE `type` `type` varchar(5) NOT NULL;
ALTER TABLE `wp_wftrafficrates` CHANGE `IP` `IP` binary(255) NOT NULL DEFAULT '\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0';
ALTER TABLE `wp_rg_lead_detail_long` CHANGE `value` `value` longtext;
ALTER TABLE `wp_ecpt_taxonomies` CHANGE `id` `id` int(9) NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_rg_incomplete_submissions` CHANGE `form_id` `form_id` int(8) unsigned NOT NULL;
ALTER TABLE `wp_commentmeta` CHANGE `meta_value` `meta_value` longtext;
ALTER TABLE `wp_rg_incomplete_submissions` CHANGE `uuid` `uuid` varchar(32) NOT NULL;
ALTER TABLE `wp_redirection_items` CHANGE `action_type` `action_type` varchar(20) NOT NULL;
ALTER TABLE `wp_redirection_logs` CHANGE `referrer` `referrer` mediumtext;
ALTER TABLE `wp_redirection_logs` CHANGE `agent` `agent` mediumtext NOT NULL;
ALTER TABLE `wp_redirection_logs` CHANGE `sent_to` `sent_to` mediumtext;
ALTER TABLE `wp_redirection_logs` CHANGE `url` `url` mediumtext NOT NULL;
ALTER TABLE `wp_em_modals` CHANGE `name` `name` varchar(150) NOT NULL DEFAULT '';
ALTER TABLE `wp_redirection_items` CHANGE `title` `title` text;
ALTER TABLE `wp_esign_users` CHANGE `uuid` `uuid` char(36) NOT NULL;
ALTER TABLE `wp_redirection_items` CHANGE `action_data` `action_data` mediumtext;
ALTER TABLE `wp_redirection_items` CHANGE `status` `status` varchar(255) NOT NULL DEFAULT 'enabled';
ALTER TABLE `wp_redirects` CHANGE `id` `id` int(9) NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_redirection_items` CHANGE `url` `url` mediumtext NOT NULL;
ALTER TABLE `wp_em_modals` CHANGE `title` `title` varchar(255) DEFAULT NULL;
ALTER TABLE `wp_redirection_groups` CHANGE `status` `status` varchar(255) NOT NULL DEFAULT 'enabled';
ALTER TABLE `wp_redirection_groups` CHANGE `name` `name` varchar(50) NOT NULL;
ALTER TABLE `wp_em_modals` CHANGE `content` `content` longtext;
ALTER TABLE `wp_redirection_404` CHANGE `ip` `ip` varchar(45) DEFAULT NULL;
ALTER TABLE `wp_redirection_404` CHANGE `referrer` `referrer` varchar(255) DEFAULT NULL;
ALTER TABLE `wp_redirection_404` CHANGE `agent` `agent` varchar(255) DEFAULT NULL;
ALTER TABLE `wp_redirection_logs` CHANGE `ip` `ip` varchar(45) DEFAULT NULL;
ALTER TABLE `wp_redirects` CHANGE `count` `count` int(9) NOT NULL DEFAULT '0';
ALTER TABLE `wp_signups` CHANGE `path` `path` varchar(100) NOT NULL DEFAULT '';
ALTER TABLE `wp_rg_form_meta` CHANGE `confirmations` `confirmations` longtext;
ALTER TABLE `wp_em_modal_metas` CHANGE `id` `id` int(9) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_rg_form_view` CHANGE `count` `count` int(8) unsigned NOT NULL DEFAULT '1';
ALTER TABLE `wp_rg_form_view` CHANGE `ip` `ip` varchar(15) DEFAULT NULL;
ALTER TABLE `wp_rg_form_view` CHANGE `form_id` `form_id` int(8) unsigned NOT NULL;
ALTER TABLE `wp_commentmeta` CHANGE `meta_key` `meta_key` varchar(255) DEFAULT NULL;
ALTER TABLE `wp_em_modal_metas` CHANGE `modal_id` `modal_id` int(9) unsigned NOT NULL;
ALTER TABLE `wp_em_modal_metas` CHANGE `display` `display` longtext;
ALTER TABLE `wp_rg_form_meta` CHANGE `notifications` `notifications` longtext;
ALTER TABLE `wp_yoast_seo_links` CHANGE `url` `url` varchar(255) NOT NULL;
ALTER TABLE `wp_em_modals` CHANGE `theme_id` `theme_id` int(9) unsigned NOT NULL DEFAULT '1';
ALTER TABLE `wp_rg_form_meta` CHANGE `entries_grid_meta` `entries_grid_meta` longtext;
ALTER TABLE `wp_rg_form_meta` CHANGE `display_meta` `display_meta` longtext;
ALTER TABLE `wp_rg_form_meta` CHANGE `form_id` `form_id` int(8) unsigned NOT NULL;
ALTER TABLE `wp_em_modal_metas` CHANGE `close` `close` longtext;
ALTER TABLE `wp_yoast_seo_links` CHANGE `type` `type` varchar(8) NOT NULL;
ALTER TABLE `wp_rg_form` CHANGE `title` `title` varchar(150) NOT NULL;
ALTER TABLE `wp_rg_form` CHANGE `id` `id` int(8) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_em_modals` CHANGE `id` `id` int(9) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_signups` CHANGE `domain` `domain` varchar(200) NOT NULL DEFAULT '';
ALTER TABLE `wp_signups` CHANGE `title` `title` longtext NOT NULL;
ALTER TABLE `wp_comments` CHANGE `comment_author_IP` `comment_author_IP` varchar(100) NOT NULL DEFAULT '';
ALTER TABLE `wp_wfpendingissues` CHANGE `ignoreP` `ignoreP` varchar(32) NOT NULL;
ALTER TABLE `wp_wfhits` CHANGE `newVisit` `newVisit` int(3) unsigned NOT NULL;
ALTER TABLE `wp_wfhits` CHANGE `isGoogle` `isGoogle` int(4) NOT NULL;
ALTER TABLE `wp_wfhits` CHANGE `jsRun` `jsRun` int(4) DEFAULT '0';
ALTER TABLE `wp_wfhits` CHANGE `IP` `IP` binary(255) DEFAULT NULL;
ALTER TABLE `wp_wfhits` CHANGE `ctime` `ctime` float(17,6) unsigned NOT NULL;
ALTER TABLE `wp_wfhits` CHANGE `attackLogTime` `attackLogTime` float(17,6) unsigned NOT NULL;
ALTER TABLE `wp_ecpt_meta_box_fields` CHANGE `id` `id` int(9) NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_wffilemods` CHANGE `SHAC` `SHAC` binary(32) NOT NULL DEFAULT '\\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0';
ALTER TABLE `wp_wfhoover` CHANGE `hostKey` `hostKey` binary(124) DEFAULT NULL;
ALTER TABLE `wp_wffilemods` CHANGE `newMD5` `newMD5` binary(255) NOT NULL;
ALTER TABLE `wp_wffilemods` CHANGE `oldMD5` `oldMD5` binary(255) NOT NULL;
ALTER TABLE `wp_wffilemods` CHANGE `knownFile` `knownFile` int(3) unsigned NOT NULL;
ALTER TABLE `wp_wffilemods` CHANGE `filenameMD5` `filenameMD5` binary(255) NOT NULL;
ALTER TABLE `wp_ecpt_meta_box_fields` CHANGE `list_order` `list_order` int(4) NOT NULL;
ALTER TABLE `wp_wffilechanges` CHANGE `md5` `md5` varchar(32) NOT NULL;
ALTER TABLE `wp_wffilechanges` CHANGE `filenameHash` `filenameHash` varchar(64) NOT NULL;
ALTER TABLE `wp_ecpt_meta_box_fields` CHANGE `rich_editor` `rich_editor` int(4) NOT NULL;
ALTER TABLE `wp_wfpendingissues` CHANGE `severity` `severity` int(3) unsigned NOT NULL;
ALTER TABLE `wp_wfissues` CHANGE `severity` `severity` int(3) unsigned NOT NULL;
ALTER TABLE `wp_wfcrawlers` CHANGE `patternSig` `patternSig` binary(255) NOT NULL;
ALTER TABLE `wp_wflogins` CHANGE `ctime` `ctime` float(17,6) unsigned NOT NULL;
ALTER TABLE `wp_wfls_settings` CHANGE `autoload` `autoload` varchar(255) NOT NULL DEFAULT 'yes';
ALTER TABLE `wp_comments` CHANGE `comment_content` `comment_content` text NOT NULL;
ALTER TABLE `wp_wfls_2fa_secrets` CHANGE `mode` `mode` varchar(255) NOT NULL DEFAULT 'authenticator';
ALTER TABLE `wp_wfls_2fa_secrets` CHANGE `recovery` `recovery` binary(255) NOT NULL;
ALTER TABLE `wp_wfls_2fa_secrets` CHANGE `secret` `secret` binary(255) NOT NULL;
ALTER TABLE `wp_comments` CHANGE `comment_approved` `comment_approved` varchar(20) NOT NULL DEFAULT '1';
ALTER TABLE `wp_wflogins` CHANGE `IP` `IP` binary(255) DEFAULT NULL;
ALTER TABLE `wp_wflogins` CHANGE `fail` `fail` int(3) unsigned NOT NULL;
ALTER TABLE `wp_comments` CHANGE `comment_agent` `comment_agent` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `wp_wfissues` CHANGE `ignoreP` `ignoreP` varchar(32) NOT NULL;
ALTER TABLE `wp_wflocs` CHANGE `countryCode` `countryCode` varchar(2) DEFAULT '';
ALTER TABLE `wp_wflocs` CHANGE `failed` `failed` int(3) unsigned NOT NULL;
ALTER TABLE `wp_wflocs` CHANGE `IP` `IP` binary(255) NOT NULL DEFAULT '\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0';
ALTER TABLE `wp_comments` CHANGE `comment_author_url` `comment_author_url` varchar(200) NOT NULL DEFAULT '';
ALTER TABLE `wp_comments` CHANGE `comment_type` `comment_type` varchar(20) NOT NULL DEFAULT '';
ALTER TABLE `wp_wflivetraffichuman` CHANGE `identifier` `identifier` binary(32) NOT NULL DEFAULT '\\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0';
ALTER TABLE `wp_wflivetraffichuman` CHANGE `IP` `IP` binary(255) NOT NULL DEFAULT '\\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0';
ALTER TABLE `wp_wfissues` CHANGE `ignoreC` `ignoreC` varchar(32) NOT NULL;
ALTER TABLE `wp_wfcrawlers` CHANGE `status` `status` varchar(8) NOT NULL;
ALTER TABLE `wp_wfcrawlers` CHANGE `IP` `IP` binary(255) NOT NULL DEFAULT '\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0';
ALTER TABLE `wp_signups` CHANGE `user_login` `user_login` varchar(60) NOT NULL DEFAULT '';
ALTER TABLE `wp_term_taxonomy` CHANGE `description` `description` longtext NOT NULL;
ALTER TABLE `wp_terms` CHANGE `slug` `slug` varchar(200) NOT NULL DEFAULT '';
ALTER TABLE `wp_terms` CHANGE `name` `name` varchar(200) NOT NULL DEFAULT '';
ALTER TABLE `wp_ecpt_post_types` CHANGE `author` `author` int(4) NOT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `thumbnail` `thumbnail` int(4) NOT NULL;
ALTER TABLE `wp_termmeta` CHANGE `meta_value` `meta_value` longtext;
ALTER TABLE `wp_termmeta` CHANGE `meta_key` `meta_key` varchar(255) DEFAULT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `excerpt` `excerpt` int(4) NOT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `fields` `fields` int(4) NOT NULL;
ALTER TABLE `wp_term_taxonomy` CHANGE `taxonomy` `taxonomy` varchar(32) NOT NULL DEFAULT '';
ALTER TABLE `wp_wfreversecache` CHANGE `IP` `IP` binary(255) NOT NULL DEFAULT '\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0';
ALTER TABLE `wp_ecpt_post_types` CHANGE `comments` `comments` int(4) NOT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `revisions` `revisions` int(4) NOT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `has_archive` `has_archive` int(4) NOT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `post_formats` `post_formats` int(4) NOT NULL;
ALTER TABLE `wp_wfstatus` CHANGE `ctime` `ctime` float(17,6) unsigned NOT NULL;
ALTER TABLE `wp_signups` CHANGE `meta` `meta` longtext;
ALTER TABLE `wp_signups` CHANGE `activation_key` `activation_key` varchar(50) NOT NULL DEFAULT '';
ALTER TABLE `wp_signups` CHANGE `user_email` `user_email` varchar(100) NOT NULL DEFAULT '';
ALTER TABLE `wp_comments` CHANGE `comment_author` `comment_author` tinytext NOT NULL;
ALTER TABLE `wp_terms` CHANGE `term_group` `term_group` bigint(20) NOT NULL DEFAULT '0';
ALTER TABLE `wp_ecpt_meta_box_fields` CHANGE `max` `max` int(4) NOT NULL;
ALTER TABLE `wp_users` CHANGE `user_url` `user_url` varchar(100) NOT NULL DEFAULT '';
ALTER TABLE `wp_wfconfig` CHANGE `autoload` `autoload` varchar(255) NOT NULL DEFAULT 'yes';
ALTER TABLE `wp_wfpendingissues` CHANGE `ignoreC` `ignoreC` varchar(32) NOT NULL;
ALTER TABLE `wp_wfblocks7` CHANGE `IP` `IP` binary(255) NOT NULL DEFAULT '\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0';
ALTER TABLE `wp_ecpt_meta_boxes` CHANGE `id` `id` int(9) NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_wfblockediplog` CHANGE `IP` `IP` binary(255) NOT NULL DEFAULT '\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0';
ALTER TABLE `wp_comments` CHANGE `comment_author_email` `comment_author_email` varchar(100) NOT NULL DEFAULT '';
ALTER TABLE `wp_users` CHANGE `display_name` `display_name` varchar(250) NOT NULL DEFAULT '';
ALTER TABLE `wp_users` CHANGE `user_activation_key` `user_activation_key` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `wp_users` CHANGE `user_email` `user_email` varchar(100) NOT NULL DEFAULT '';
ALTER TABLE `wp_ecpt_post_types` CHANGE `editor` `editor` int(4) NOT NULL;
ALTER TABLE `wp_users` CHANGE `user_nicename` `user_nicename` varchar(50) NOT NULL DEFAULT '';
ALTER TABLE `wp_users` CHANGE `user_pass` `user_pass` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `wp_users` CHANGE `user_login` `user_login` varchar(60) NOT NULL DEFAULT '';
ALTER TABLE `wp_ecpt_post_types` CHANGE `id` `id` int(9) NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_ecpt_post_types` CHANGE `hierarchical` `hierarchical` int(4) NOT NULL;
ALTER TABLE `wp_usermeta` CHANGE `meta_value` `meta_value` longtext;
ALTER TABLE `wp_usermeta` CHANGE `meta_key` `meta_key` varchar(255) DEFAULT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `title` `title` int(4) NOT NULL;
ALTER TABLE `wp_redirection_404` CHANGE `url` `url` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `wp_redirection_items` CHANGE `match_type` `match_type` varchar(20) NOT NULL;
ALTER TABLE `wp_gf_draft_submissions` CHANGE `submission` `submission` longtext NOT NULL;
ALTER TABLE `wp_hustle_modules` CHANGE `module_name` `module_name` varchar(255) NOT NULL;
ALTER TABLE `wp_links` CHANGE `link_name` `link_name` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `wp_links` CHANGE `link_url` `link_url` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `wp_hustle_modules_meta` CHANGE `meta_value` `meta_value` longtext;
ALTER TABLE `wp_hustle_modules_meta` CHANGE `meta_key` `meta_key` varchar(191) DEFAULT NULL;
ALTER TABLE `wp_esign_invitations` CHANGE `invite_hash` `invite_hash` text NOT NULL;
ALTER TABLE `wp_hustle_modules` CHANGE `test_mode` `test_mode` int(4) DEFAULT '0';
ALTER TABLE `wp_hustle_modules` CHANGE `active` `active` int(4) DEFAULT '1';
ALTER TABLE `wp_hustle_modules` CHANGE `module_type` `module_type` varchar(100) NOT NULL;
ALTER TABLE `wp_esign_invitations` CHANGE `invite_message` `invite_message` longtext NOT NULL;
ALTER TABLE `wp_links` CHANGE `link_target` `link_target` varchar(25) NOT NULL DEFAULT '';
ALTER TABLE `wp_hfcm_scripts` CHANGE `last_modified_by` `last_modified_by` varchar(300) DEFAULT NULL;
ALTER TABLE `wp_hfcm_scripts` CHANGE `created_by` `created_by` varchar(300) DEFAULT NULL;
ALTER TABLE `wp_hfcm_scripts` CHANGE `status` `status` varchar(255) NOT NULL DEFAULT 'active';
ALTER TABLE `wp_hfcm_scripts` CHANGE `s_tags` `s_tags` varchar(300) DEFAULT NULL;
ALTER TABLE `wp_hfcm_scripts` CHANGE `s_categories` `s_categories` varchar(300) DEFAULT NULL;
ALTER TABLE `wp_hfcm_scripts` CHANGE `s_custom_posts` `s_custom_posts` varchar(300) DEFAULT NULL;
ALTER TABLE `wp_gf_addon_feed` CHANGE `meta` `meta` longtext;
ALTER TABLE `wp_hfcm_scripts` CHANGE `ex_posts` `ex_posts` varchar(300) DEFAULT NULL;
ALTER TABLE `wp_links` CHANGE `link_image` `link_image` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `wp_links` CHANGE `link_description` `link_description` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `wp_hfcm_scripts` CHANGE `ex_pages` `ex_pages` varchar(300) DEFAULT NULL;
ALTER TABLE `wp_mail_bank_logs` CHANGE `email_to` `email_to` varchar(200) DEFAULT NULL;
ALTER TABLE `wp_mail_bank_logs` CHANGE `debugging_output` `debugging_output` longtext;
ALTER TABLE `wp_mail_bank_logs` CHANGE `debug_mode` `debug_mode` varchar(50) DEFAULT NULL;
ALTER TABLE `wp_mail_bank_logs` CHANGE `sender_email` `sender_email` varchar(200) DEFAULT NULL;
ALTER TABLE `wp_mail_bank_logs` CHANGE `sender_name` `sender_name` varchar(200) DEFAULT NULL;
ALTER TABLE `wp_mail_bank_logs` CHANGE `content` `content` longtext;
ALTER TABLE `wp_mail_bank_logs` CHANGE `subject` `subject` longtext;
ALTER TABLE `wp_gf_draft_submissions` CHANGE `source_url` `source_url` longtext NOT NULL;
ALTER TABLE `wp_mail_bank_logs` CHANGE `cc` `cc` varchar(200) DEFAULT NULL;
ALTER TABLE `wp_gf_addon_feed` CHANGE `form_id` `form_id` int(8) unsigned NOT NULL;
ALTER TABLE `wp_links` CHANGE `link_visible` `link_visible` varchar(20) NOT NULL DEFAULT 'Y';
ALTER TABLE `wp_esign_documents_signatures` CHANGE `ip_address` `ip_address` varchar(100) NOT NULL;
ALTER TABLE `wp_mail_bank_email_logs` CHANGE `email_data` `email_data` longtext NOT NULL;
ALTER TABLE `wp_esign_documents_signatures` CHANGE `signer_type` `signer_type` varchar(55) DEFAULT NULL;
ALTER TABLE `wp_mail_bank` CHANGE `type` `type` varchar(100) NOT NULL;
ALTER TABLE `wp_esign_documents_signer_field_data` CHANGE `input_fields` `input_fields` longtext NOT NULL;
ALTER TABLE `wp_links` CHANGE `link_rss` `link_rss` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `wp_gf_addon_feed` CHANGE `feed_order` `feed_order` int(8) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `wp_links` CHANGE `link_notes` `link_notes` mediumtext NOT NULL;
ALTER TABLE `wp_links` CHANGE `link_rel` `link_rel` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `wp_hfcm_scripts` CHANGE `s_posts` `s_posts` varchar(1000) DEFAULT NULL;
ALTER TABLE `wp_hfcm_scripts` CHANGE `s_pages` `s_pages` varchar(300) DEFAULT NULL;
ALTER TABLE `wp_esign_documents_meta` CHANGE `meta_value` `meta_value` longtext NOT NULL;
ALTER TABLE `wp_gf_entry` CHANGE `transaction_id` `transaction_id` varchar(50) DEFAULT NULL;
ALTER TABLE `wp_esign_settings` CHANGE `setting_value` `setting_value` longtext NOT NULL;
ALTER TABLE `wp_gf_draft_submissions` CHANGE `uuid` `uuid` varchar(32) NOT NULL;
ALTER TABLE `wp_gf_draft_submissions` CHANGE `email` `email` varchar(255) DEFAULT NULL;
ALTER TABLE `wp_gf_entry_meta` CHANGE `meta_value` `meta_value` longtext;
ALTER TABLE `wp_gf_entry_meta` CHANGE `meta_key` `meta_key` varchar(255) DEFAULT NULL;
ALTER TABLE `wp_gf_entry_meta` CHANGE `form_id` `form_id` int(8) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `wp_gf_draft_submissions` CHANGE `form_id` `form_id` int(8) unsigned NOT NULL;
ALTER TABLE `wp_gf_entry` CHANGE `status` `status` varchar(20) NOT NULL DEFAULT 'active';
ALTER TABLE `wp_gf_entry` CHANGE `payment_method` `payment_method` varchar(30) DEFAULT NULL;
ALTER TABLE `wp_gf_entry_notes` CHANGE `user_name` `user_name` varchar(250) DEFAULT NULL;
ALTER TABLE `wp_gf_entry` CHANGE `payment_status` `payment_status` varchar(15) DEFAULT NULL;
ALTER TABLE `wp_gf_entry` CHANGE `currency` `currency` varchar(5) DEFAULT NULL;
ALTER TABLE `wp_gf_draft_submissions` CHANGE `ip` `ip` varchar(39) NOT NULL;
ALTER TABLE `wp_gf_entry` CHANGE `user_agent` `user_agent` varchar(250) NOT NULL DEFAULT '';
ALTER TABLE `wp_gf_entry` CHANGE `source_url` `source_url` varchar(200) NOT NULL DEFAULT '';
ALTER TABLE `wp_gf_entry` CHANGE `ip` `ip` varchar(39) NOT NULL;
ALTER TABLE `wp_gf_entry` CHANGE `form_id` `form_id` int(8) unsigned NOT NULL;
ALTER TABLE `wp_esign_signatures` CHANGE `signature_type` `signature_type` varchar(20) NOT NULL DEFAULT 'full';
ALTER TABLE `wp_esign_signatures` CHANGE `signature_hash` `signature_hash` varchar(64) NOT NULL;
ALTER TABLE `wp_gf_entry_notes` CHANGE `value` `value` longtext;
ALTER TABLE `wp_hfcm_scripts` CHANGE `display_on` `display_on` varchar(255) NOT NULL DEFAULT 'All';
ALTER TABLE `wp_gf_addon_feed` CHANGE `addon_slug` `addon_slug` varchar(50) DEFAULT NULL;
ALTER TABLE `wp_hfcm_scripts` CHANGE `location` `location` varchar(100) NOT NULL;
ALTER TABLE `wp_hfcm_scripts` CHANGE `device_type` `device_type` varchar(255) DEFAULT 'both';
ALTER TABLE `wp_hfcm_scripts` CHANGE `snippet` `snippet` text;
ALTER TABLE `wp_hfcm_scripts` CHANGE `name` `name` varchar(100) DEFAULT NULL;
ALTER TABLE `wp_esign_invitations` CHANGE `sender_ip` `sender_ip` varchar(100) NOT NULL;
ALTER TABLE `wp_gf_form_view` CHANGE `count` `count` int(8) unsigned NOT NULL DEFAULT '1';
ALTER TABLE `wp_gf_form_view` CHANGE `ip` `ip` varchar(15) DEFAULT NULL;
ALTER TABLE `wp_gf_form_view` CHANGE `form_id` `form_id` int(8) unsigned NOT NULL;
ALTER TABLE `wp_gf_form_meta` CHANGE `notifications` `notifications` longtext;
ALTER TABLE `wp_gf_entry_notes` CHANGE `note_type` `note_type` varchar(50) DEFAULT NULL;
ALTER TABLE `wp_gf_form_meta` CHANGE `confirmations` `confirmations` longtext;
ALTER TABLE `wp_gf_form_meta` CHANGE `entries_grid_meta` `entries_grid_meta` longtext;
ALTER TABLE `wp_gf_form_meta` CHANGE `display_meta` `display_meta` longtext;
ALTER TABLE `wp_gf_form_meta` CHANGE `form_id` `form_id` int(8) unsigned NOT NULL;
ALTER TABLE `wp_gf_form` CHANGE `title` `title` varchar(150) NOT NULL;
ALTER TABLE `wp_gf_form` CHANGE `id` `id` int(8) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_esign_settings` CHANGE `setting_name` `setting_name` varchar(55) NOT NULL;
ALTER TABLE `wp_gf_addon_feed` CHANGE `event_type` `event_type` varchar(20) DEFAULT NULL;
ALTER TABLE `wp_gf_entry_notes` CHANGE `sub_type` `sub_type` varchar(50) DEFAULT NULL;
ALTER TABLE `wp_mail_bank_logs` CHANGE `status` `status` varchar(10) DEFAULT NULL;
ALTER TABLE `wp_mail_bank_logs` CHANGE `bcc` `bcc` varchar(200) DEFAULT NULL;
ALTER TABLE `wp_esign_documents` CHANGE `document_title` `document_title` varchar(200) NOT NULL;
ALTER TABLE `wp_esign_document_users` CHANGE `company_name` `company_name` varchar(64) NOT NULL;
ALTER TABLE `wp_em_theme_metas` CHANGE `id` `id` int(9) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_ontrix_members` CHANGE `validation_code` `validation_code` varchar(8) DEFAULT NULL;
ALTER TABLE `wp_esign_documents` CHANGE `document_uri` `document_uri` text;
ALTER TABLE `wp_posts` CHANGE `post_content` `post_content` longtext NOT NULL;
ALTER TABLE `wp_esign_documents` CHANGE `document_checksum` `document_checksum` text NOT NULL;
ALTER TABLE `wp_esign_documents` CHANGE `document_status` `document_status` varchar(24) NOT NULL;
ALTER TABLE `wp_esign_documents` CHANGE `document_type` `document_type` varchar(255) NOT NULL DEFAULT 'normal';
ALTER TABLE `wp_ontrix_projectapplications` CHANGE `admin_log` `admin_log` varchar(32) NOT NULL;
ALTER TABLE `wp_esign_users` CHANGE `last_name` `last_name` varchar(65) NOT NULL;
ALTER TABLE `wp_esign_users` CHANGE `first_name` `first_name` varchar(45) NOT NULL;
ALTER TABLE `wp_esign_users` CHANGE `user_title` `user_title` varchar(55) NOT NULL DEFAULT '';
ALTER TABLE `wp_esign_documents` CHANGE `document_content` `document_content` longtext NOT NULL;
ALTER TABLE `wp_esign_users` CHANGE `user_email` `user_email` varchar(100) NOT NULL;
ALTER TABLE `wp_ontrix_questionsets` CHANGE `active` `active` int(11) NOT NULL DEFAULT '1';
ALTER TABLE `wp_esign_document_users` CHANGE `signer_email` `signer_email` varchar(64) NOT NULL;
ALTER TABLE `wp_posts` CHANGE `post_title` `post_title` text NOT NULL;
ALTER TABLE `wp_options` CHANGE `option_name` `option_name` varchar(191) NOT NULL DEFAULT '';
ALTER TABLE `wp_postmeta` CHANGE `meta_value` `meta_value` longtext;
ALTER TABLE `wp_postmeta` CHANGE `meta_key` `meta_key` varchar(255) DEFAULT NULL;
ALTER TABLE `wp_em_theme_metas` CHANGE `overlay` `overlay` longtext;
ALTER TABLE `wp_em_theme_metas` CHANGE `container` `container` longtext;
ALTER TABLE `wp_options` CHANGE `autoload` `autoload` varchar(20) NOT NULL DEFAULT 'yes';
ALTER TABLE `wp_options` CHANGE `option_value` `option_value` longtext NOT NULL;
ALTER TABLE `wp_em_theme_metas` CHANGE `close` `close` longtext;
ALTER TABLE `wp_esign_document_users` CHANGE `signer_name` `signer_name` varchar(64) NOT NULL;
ALTER TABLE `wp_em_theme_metas` CHANGE `title` `title` longtext;
ALTER TABLE `wp_em_theme_metas` CHANGE `content` `content` longtext;
ALTER TABLE `wp_em_themes` CHANGE `id` `id` int(9) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_ontrix_smsstatus_old` CHANGE `id` `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_ontrix_smsstatus` CHANGE `id` `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_em_themes` CHANGE `name` `name` varchar(150) NOT NULL DEFAULT '';
ALTER TABLE `wp_ontrix_members` CHANGE `sex` `sex` tinyint(1) DEFAULT '1';
ALTER TABLE `wp_ontrix_members` CHANGE `admin_note` `admin_note` text;
ALTER TABLE `wp_posts` CHANGE `post_excerpt` `post_excerpt` text NOT NULL;
ALTER TABLE `wp_esign_documents_fields_data` CHANGE `value` `value` longtext NOT NULL;
ALTER TABLE `wp_ontrix_bulkemails_email` CHANGE `id` `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_posts` CHANGE `post_password` `post_password` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `wp_posts` CHANGE `post_name` `post_name` varchar(200) NOT NULL DEFAULT '';
ALTER TABLE `wp_esign_documents_fields_data` CHANGE `field_id` `field_id` varchar(100) NOT NULL;
ALTER TABLE `wp_posts` CHANGE `to_ping` `to_ping` text NOT NULL;
ALTER TABLE `wp_posts` CHANGE `pinged` `pinged` text NOT NULL;
ALTER TABLE `wp_posts` CHANGE `post_content_filtered` `post_content_filtered` longtext NOT NULL;
ALTER TABLE `wp_esign_documents` CHANGE `ip_address` `ip_address` varchar(100) NOT NULL;
ALTER TABLE `wp_posts` CHANGE `guid` `guid` varchar(255) NOT NULL DEFAULT '';
ALTER TABLE `wp_posts` CHANGE `post_type` `post_type` varchar(20) NOT NULL DEFAULT 'post';
ALTER TABLE `wp_posts` CHANGE `post_mime_type` `post_mime_type` varchar(100) NOT NULL DEFAULT '';
ALTER TABLE `wp_ontrix_admin` CHANGE `last_login` `last_login` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `wp_mail_bank_meta` CHANGE `meta_value` `meta_value` longtext NOT NULL;
ALTER TABLE `wp_mail_bank_meta` CHANGE `meta_key` `meta_key` varchar(255) NOT NULL;
ALTER TABLE `wp_esign_documents_meta` CHANGE `meta_key` `meta_key` varchar(255) NOT NULL;
ALTER TABLE `wp_posts` CHANGE `ping_status` `ping_status` varchar(20) NOT NULL DEFAULT 'open';
ALTER TABLE `wp_ontrix_bulkemails_members` CHANGE `messageid` `messageid` bigint(20) NOT NULL;
ALTER TABLE `wp_em_theme_metas` CHANGE `theme_id` `theme_id` int(9) unsigned NOT NULL;
ALTER TABLE `wp_esign_documents_events` CHANGE `event` `event` varchar(20) NOT NULL;
ALTER TABLE `wp_ontrix_memberprojectica` CHANGE `i_agree` `i_agree` int(4) NOT NULL DEFAULT '1';
ALTER TABLE `wp_ontrix_memberprojectica` CHANGE `icaid` `icaid` bigint(20) NOT NULL DEFAULT '0';
ALTER TABLE `wp_ontrix_memberprojectica` CHANGE `projectid` `projectid` bigint(20) NOT NULL DEFAULT '0';
ALTER TABLE `wp_ontrix_memberprojectica` CHANGE `memberid` `memberid` bigint(20) unsigned NOT NULL;
ALTER TABLE `wp_posts` CHANGE `post_status` `post_status` varchar(20) NOT NULL DEFAULT 'publish';
ALTER TABLE `wp_esign_signatures` CHANGE `signature_data` `signature_data` longtext NOT NULL;
ALTER TABLE `wp_ontrix_ica` CHANGE `ica_id` `ica_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_esign_documents_events` CHANGE `event_data` `event_data` varchar(256) NOT NULL;
ALTER TABLE `wp_posts` CHANGE `comment_status` `comment_status` varchar(20) NOT NULL DEFAULT 'open';
ALTER TABLE `wp_esign_signatures` CHANGE `signature_salt` `signature_salt` varchar(40) NOT NULL;
ALTER TABLE `wp_gf_addon_feed` CHANGE `id` `id` int(8) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_esign_documents_events` CHANGE `ip_address` `ip_address` varchar(100) NOT NULL;
ALTER TABLE `wp_wflogins` ADD KEY `IP` (`IP`,`fail`);
ALTER TABLE `wp_wfhits` ADD KEY `IP` (`IP`,`ctime`);
ALTER TABLE `wp_gf_entry` ADD KEY `form_id_2` (`form_id`,`status`);
ALTER TABLE `wp_comments` ADD KEY `comment_approved` (`comment_approved`,`comment_date_gmt`);
ALTER TABLE `wp_wfhoover` ADD KEY `hostKey` (`hostKey`);
ALTER TABLE `wp_yoast_seo_links` ADD KEY `post_id` (`post_id`,`type`);
ALTER TABLE `wp_wfhits` ADD KEY `ctime` (`ctime`);
ALTER TABLE `wp_gf_addon_feed` ADD KEY `addon_slug` (`addon_slug`,`form_id`);
ALTER TABLE `wp_redirection_items` ADD KEY `group_id` (`group_id`,`position`);
ALTER TABLE `wp_term_taxonomy` ADD UNIQUE KEY `term_id` (`term_id`,`taxonomy`);
ALTER TABLE `wp_redirection_items` ADD KEY `group_id_2` (`group_id`);
ALTER TABLE `wp_ontrix_projectapplications` ADD KEY `projectid_2` (`projectid`,`denied`);
ALTER TABLE `wp_ontrix_admin_old` ADD UNIQUE KEY `email` (`email`);
ALTER TABLE `wp_rg_lead_detail` ADD KEY `lead_id_2` (`lead_id`,`field_number`);
ALTER TABLE `wp_posts` ADD KEY `post_type` (`post_type`,`post_status`,`post_date`,`ID`);
ALTER TABLE `wp_wfstatus` ADD KEY `type` (`type`);
ALTER TABLE `wp_rg_lead_meta` ADD KEY `form_id` (`form_id`,`meta_key`);
ALTER TABLE `wp_signups` ADD KEY `user_login` (`user_login`,`user_email`);
ALTER TABLE `wp_ontrix_projectapplications` ADD KEY `projectid` (`projectid`,`approved`);
ALTER TABLE `wp_users` ADD KEY `user_login` (`user_login`);
ALTER TABLE `wp_ontrix_projectapplications` ADD KEY `projectid_3` (`projectid`,`confirmation`);
ALTER TABLE `wp_wfstatus` ADD KEY `ctime` (`ctime`);
ALTER TABLE `wp_ontrix_projectapplications` ADD KEY `projectid_4` (`projectid`);
ALTER TABLE `wp_rg_lead_notes` ADD KEY `lead_id_2` (`lead_id`,`user_id`);
ALTER TABLE `wp_gf_entry_notes` ADD KEY `entry_id_2` (`entry_id`,`user_id`);
ALTER TABLE `wp_signups` ADD KEY `domain` (`domain`,`path`);
ALTER TABLE `wp_rg_lead_meta` DROP INDEX `meta_key`;
ALTER TABLE `wp_rg_lead_meta` ADD KEY `meta_key` (`meta_key`);
ALTER TABLE `wp_commentmeta` DROP INDEX `meta_key`;
ALTER TABLE `wp_commentmeta` ADD KEY `meta_key` (`meta_key`);
ALTER TABLE `wp_redirection_404` DROP INDEX `url`;
ALTER TABLE `wp_redirection_404` ADD KEY `url` (`url`);
ALTER TABLE `wp_redirection_404` DROP INDEX `referrer`;
ALTER TABLE `wp_redirection_404` ADD KEY `referrer` (`referrer`);
ALTER TABLE `wp_posts` DROP INDEX `post_name`;
ALTER TABLE `wp_posts` ADD KEY `post_name` (`post_name`);
ALTER TABLE `wp_termmeta` DROP INDEX `meta_key`;
ALTER TABLE `wp_termmeta` ADD KEY `meta_key` (`meta_key`);
ALTER TABLE `wp_esign_documents_events` DROP INDEX `event_data`;
ALTER TABLE `wp_esign_documents_events` ADD KEY `event_data` (`event_data`);
ALTER TABLE `wp_terms` DROP INDEX `slug`;
ALTER TABLE `wp_terms` ADD KEY `slug` (`slug`);
ALTER TABLE `wp_terms` DROP INDEX `name`;
ALTER TABLE `wp_terms` ADD KEY `name` (`name`);
ALTER TABLE `wp_comments` DROP INDEX `comment_author_email`;
ALTER TABLE `wp_comments` ADD KEY `comment_author_email` (`comment_author_email`);
ALTER TABLE `wp_gf_entry_meta` DROP INDEX `meta_key`;
ALTER TABLE `wp_gf_entry_meta` ADD KEY `meta_key` (`meta_key`);
ALTER TABLE `wp_usermeta` DROP INDEX `meta_key`;
ALTER TABLE `wp_usermeta` ADD KEY `meta_key` (`meta_key`);
ALTER TABLE `wp_postmeta` DROP INDEX `meta_key`;
ALTER TABLE `wp_postmeta` ADD KEY `meta_key` (`meta_key`);
ALTER TABLE `wp_wfstatus` DROP INDEX `k1`;
ALTER TABLE `wp_gf_addon_feed` DROP INDEX `addon_form`;
ALTER TABLE `wp_yoast_seo_links` DROP INDEX `link_direction`;
ALTER TABLE `wp_wfstatus` DROP INDEX `k2`;
ALTER TABLE `wp_posts` DROP INDEX `type_status_date`;
ALTER TABLE `wp_wflogins` DROP INDEX `k1`;
ALTER TABLE `wp_ontrix_admin` DROP INDEX `NewIndex1`;
ALTER TABLE `wp_redirection_items` DROP INDEX `url`;
ALTER TABLE `wp_redirection_items` DROP INDEX `group_idpos`;
ALTER TABLE `wp_redirection_items` DROP INDEX `group`;
ALTER TABLE `wp_ontrix_projectapplications` DROP INDEX `IDX_PROJ_CONF`;
ALTER TABLE `wp_ontrix_projectapplications` DROP INDEX `IDX_PROJ_DEN`;
ALTER TABLE `wp_ontrix_projectapplications` DROP INDEX `IDX_PROJ_APPR`;
ALTER TABLE `wp_esign_documents` DROP INDEX `document_checksum`;
ALTER TABLE `wp_rg_lead_detail` DROP INDEX `lead_field_number`;
ALTER TABLE `wp_rg_lead_detail` DROP INDEX `lead_field_value`;
ALTER TABLE `wp_ontrix_admin_old` DROP INDEX `NewIndex1`;
ALTER TABLE `wp_rg_lead_meta` DROP INDEX `form_id_meta_key`;
ALTER TABLE `wp_rg_lead_notes` DROP INDEX `lead_user_key`;
ALTER TABLE `wp_gf_entry` DROP INDEX `form_id_status`;
ALTER TABLE `wp_signups` DROP INDEX `user_login_email`;
ALTER TABLE `wp_signups` DROP INDEX `domain_path`;
ALTER TABLE `wp_term_taxonomy` DROP INDEX `term_id_taxonomy`;
ALTER TABLE `wp_users` DROP INDEX `user_login_key`;
ALTER TABLE `wp_esign_invitations` DROP INDEX `invite_hash`;
ALTER TABLE `wp_gf_entry_notes` DROP INDEX `entry_user_key`;
ALTER TABLE `wp_wfhits` DROP INDEX `k1`;
ALTER TABLE `wp_wfhits` DROP INDEX `k2`;
ALTER TABLE `wp_wfhoover` DROP INDEX `k2`;
ALTER TABLE `wp_gf_entry_meta` DROP INDEX `meta_value`;
ALTER TABLE `wp_comments` DROP INDEX `comment_approved_date_gmt`;
ALTER TABLE `wp_ontrix_projectapplications` DROP INDEX `IDX_PROJ_ID`;
"""
SQL_DOWN = u"""
ALTER TABLE `wp_rg_form_view` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_menus` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_projectapplications` ENGINE = MyISAM;
ALTER TABLE `wp_rg_lead_meta` ENGINE = MyISAM;
ALTER TABLE `wp_ecpt_taxonomies` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_phonetype` ENGINE = MyISAM;
ALTER TABLE `wp_rg_lead_notes` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_pages` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_members` ENGINE = MyISAM;
ALTER TABLE `wp_rg_lead_detail` ENGINE = MyISAM;
ALTER TABLE `wp_signups` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_membergroup` ENGINE = MyISAM;
ALTER TABLE `wp_term_relationships` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_groups` ENGINE = MyISAM;
ALTER TABLE `wp_term_taxonomy` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_group` ENGINE = MyISAM;
ALTER TABLE `wp_rg_lead_detail_long` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_projects` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_ethnicity` ENGINE = MyISAM;
ALTER TABLE `wp_rg_form` ENGINE = MyISAM;
ALTER TABLE `wp_posts` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_union` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_twilio_numbers` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_tickets` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_sms_log_old` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_sms_log` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_roles` ENGINE = MyISAM;
ALTER TABLE `wp_rg_lead` ENGINE = MyISAM;
ALTER TABLE `wp_rg_form_meta` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_relationtypes` ENGINE = MyISAM;
ALTER TABLE `wp_gf_addon_feed` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_relations` ENGINE = MyISAM;
ALTER TABLE `wp_rg_incomplete_submissions` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_projecttype` ENGINE = MyISAM;
ALTER TABLE `wp_termmeta` ENGINE = MyISAM;
ALTER TABLE `wp_terms` ENGINE = MyISAM;
ALTER TABLE `wp_postmeta` ENGINE = MyISAM;
ALTER TABLE `wp_mail_bank_meta` ENGINE = MyISAM;
ALTER TABLE `wp_commentmeta` ENGINE = MyISAM;
ALTER TABLE `wp_yoast_seo_meta` ENGINE = MyISAM;
ALTER TABLE `wp_yoast_seo_links` ENGINE = MyISAM;
ALTER TABLE `wp_comments` ENGINE = MyISAM;
ALTER TABLE `wp_links` ENGINE = MyISAM;
ALTER TABLE `wp_mail_bank` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_citylivein` ENGINE = MyISAM;
ALTER TABLE `wp_ecpt_meta_box_fields` ENGINE = MyISAM;
ALTER TABLE `wp_mail_bank_logs` ENGINE = MyISAM;
ALTER TABLE `wp_options` ENGINE = MyISAM;
ALTER TABLE `wp_ecpt_meta_boxes` ENGINE = MyISAM;
ALTER TABLE `wp_usermeta` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_admin` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_bulkemails_members` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_admin_old` ENGINE = MyISAM;
ALTER TABLE `wp_ecpt_post_types` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_age` ENGINE = MyISAM;
ALTER TABLE `wp_users` ENGINE = MyISAM;
ALTER TABLE `wp_ontrix_bulkemails_email` ENGINE = MyISAM;
ALTER TABLE `wp_mail_bank_meta` DEFAULT COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_gf_entry_notes` DEFAULT COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_gf_draft_submissions` DEFAULT COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_gf_entry` DEFAULT COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_gf_entry_meta` DEFAULT COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_hfcm_scripts` DEFAULT COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_gf_form` DEFAULT COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_gf_form_meta` DEFAULT COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_gf_form_view` DEFAULT COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_mail_bank_logs` DEFAULT COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_hustle_modules` DEFAULT COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_hustle_modules_meta` DEFAULT COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_links` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_mail_bank` DEFAULT COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_mail_bank_email_logs` DEFAULT COLLATE utf8mb4_unicode_ci;
ALTER TABLE `states` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `clients` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_options` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_wflocs` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_wfconfig` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_wfcrawlers` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_wffilechanges` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_wffilemods` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_wfhits` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_wfhoover` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_wfissues` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_wfknownfilelist` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_wflivetraffichuman` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_wflogins` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_wfblockediplog` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_wfls_2fa_secrets` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_wfls_settings` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_wfnotifications` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_wfpendingissues` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_wfreversecache` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_wfsnipcache` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_wfstatus` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_wftrafficrates` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_yoast_seo_links` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_wfblocks7` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_users` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_postmeta` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_rg_lead` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_posts` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_redirection_404` DEFAULT COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_redirection_groups` DEFAULT COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_redirection_items` DEFAULT COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_redirection_logs` DEFAULT COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_rg_form` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_rg_form_meta` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_rg_form_view` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_rg_incomplete_submissions` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_rg_lead_detail` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_usermeta` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_rg_lead_detail_long` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_rg_lead_meta` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_rg_lead_notes` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_sgpb_subscribers` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_sgpb_subscription_error_log` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_signups` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_term_relationships` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_term_taxonomy` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_termmeta` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_terms` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_gf_addon_feed` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_yoast_seo_meta` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_esign_users` DEFAULT COLLATE utf8_unicode_ci;
ALTER TABLE `wp_esign_documents_meta` DEFAULT COLLATE utf8_unicode_ci;
ALTER TABLE `wp_esign_settings` DEFAULT COLLATE utf8_unicode_ci;
ALTER TABLE `wp_ecpt_meta_boxes` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_ecpt_post_types` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_esign_invitations` DEFAULT COLLATE utf8_unicode_ci;
ALTER TABLE `wp_esign_documents_stand_alone_docs` DEFAULT COLLATE utf8_unicode_ci;
ALTER TABLE `wp_em_theme_metas` DEFAULT COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_esign_documents_signatures` DEFAULT COLLATE utf8_unicode_ci;
ALTER TABLE `wp_esign_documents_fields_data` DEFAULT COLLATE utf8_unicode_ci;
ALTER TABLE `wp_esign_signatures` DEFAULT COLLATE utf8_unicode_ci;
ALTER TABLE `wp_ecpt_taxonomies` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_esign_documents_events` DEFAULT COLLATE utf8_unicode_ci;
ALTER TABLE `wp_em_modal_metas` DEFAULT COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_esign_documents` DEFAULT COLLATE utf8_unicode_ci;
ALTER TABLE `wp_esign_document_users` DEFAULT COLLATE utf8_unicode_ci;
ALTER TABLE `wp_em_themes` DEFAULT COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_em_modals` DEFAULT COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_ecpt_meta_box_fields` DEFAULT COLLATE utf8_general_ci;
ALTER TABLE `wp_esign_documents_signer_field_data` DEFAULT COLLATE utf8_unicode_ci;
ALTER TABLE `wp_comments` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_commentmeta` DEFAULT COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_rg_lead` CHANGE `user_agent` `user_agent` varchar(250) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_ecpt_taxonomies` CHANGE `show_tagcloud` `show_tagcloud` tinyint(4) NOT NULL;
ALTER TABLE `wp_ecpt_taxonomies` CHANGE `show_in_nav_menus` `show_in_nav_menus` tinyint(4) NOT NULL;
ALTER TABLE `wp_rg_lead` CHANGE `status` `status` varchar(20) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT 'active';
ALTER TABLE `wp_rg_lead` CHANGE `transaction_id` `transaction_id` varchar(50) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL;
ALTER TABLE `wp_rg_lead` CHANGE `payment_method` `payment_method` varchar(30) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL;
ALTER TABLE `wp_rg_lead` CHANGE `payment_status` `payment_status` varchar(15) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL;
ALTER TABLE `wp_rg_lead` CHANGE `currency` `currency` varchar(5) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL;
ALTER TABLE `wp_wfnotifications` CHANGE `new` `new` tinyint(3) unsigned NOT NULL DEFAULT '1';
ALTER TABLE `wp_rg_lead_detail` CHANGE `form_id` `form_id` mediumint(8) unsigned NOT NULL;
ALTER TABLE `wp_rg_lead` CHANGE `source_url` `source_url` varchar(200) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_rg_lead` CHANGE `ip` `ip` varchar(39) COLLATE utf8mb4_unicode_520_ci NOT NULL;
ALTER TABLE `wp_rg_lead` CHANGE `form_id` `form_id` mediumint(8) unsigned NOT NULL;
ALTER TABLE `wp_ecpt_taxonomies` CHANGE `with_front` `with_front` tinyint(4) NOT NULL;
ALTER TABLE `wp_ecpt_taxonomies` CHANGE `enable_filter` `enable_filter` tinyint(4) NOT NULL;
ALTER TABLE `wp_rg_incomplete_submissions` CHANGE `submission` `submission` longtext COLLATE utf8mb4_unicode_520_ci NOT NULL;
ALTER TABLE `wp_rg_incomplete_submissions` CHANGE `source_url` `source_url` longtext COLLATE utf8mb4_unicode_520_ci NOT NULL;
ALTER TABLE `wp_rg_incomplete_submissions` CHANGE `ip` `ip` varchar(39) COLLATE utf8mb4_unicode_520_ci NOT NULL;
ALTER TABLE `wp_wftrafficrates` CHANGE `hitType` `hitType` enum('hit','404') NOT NULL DEFAULT 'hit';
ALTER TABLE `wp_ecpt_taxonomies` CHANGE `hierarchical` `hierarchical` tinyint(4) NOT NULL;
ALTER TABLE `wp_rg_lead_detail` CHANGE `value` `value` longtext COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_ecpt_post_types` CHANGE `with_front` `with_front` tinyint(4) NOT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `page_attributes` `page_attributes` tinyint(4) NOT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `show_in_nav_menus` `show_in_nav_menus` tinyint(4) NOT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `menu_position` `menu_position` tinyint(4) NOT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `exclude_from_search` `exclude_from_search` tinyint(4) NOT NULL;
ALTER TABLE `wp_rg_lead_notes` CHANGE `note_type` `note_type` varchar(50) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL;
ALTER TABLE `wp_rg_lead_notes` CHANGE `value` `value` longtext COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_rg_lead_notes` CHANGE `user_name` `user_name` varchar(250) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL;
ALTER TABLE `wp_wfstatus` CHANGE `level` `level` tinyint(3) unsigned NOT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `post_tags` `post_tags` tinyint(4) NOT NULL;
ALTER TABLE `wp_rg_incomplete_submissions` CHANGE `email` `email` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL;
ALTER TABLE `wp_rg_lead_meta` CHANGE `meta_value` `meta_value` longtext COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_rg_lead_meta` CHANGE `meta_key` `meta_key` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL;
ALTER TABLE `wp_rg_lead_meta` CHANGE `form_id` `form_id` mediumint(8) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `wp_ecpt_post_types` CHANGE `categories` `categories` tinyint(4) NOT NULL;
ALTER TABLE `wp_wfstatus` CHANGE `type` `type` char(5) NOT NULL;
ALTER TABLE `wp_wftrafficrates` CHANGE `IP` `IP` binary(16) NOT NULL DEFAULT '\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0';
ALTER TABLE `wp_rg_lead_detail_long` CHANGE `value` `value` longtext COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_ecpt_taxonomies` CHANGE `id` `id` mediumint(9) NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_rg_incomplete_submissions` CHANGE `form_id` `form_id` mediumint(8) unsigned NOT NULL;
ALTER TABLE `wp_commentmeta` CHANGE `meta_value` `meta_value` longtext COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_rg_incomplete_submissions` CHANGE `uuid` `uuid` char(32) COLLATE utf8mb4_unicode_520_ci NOT NULL;
ALTER TABLE `wp_redirection_items` CHANGE `action_type` `action_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `wp_redirection_logs` CHANGE `referrer` `referrer` mediumtext COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_redirection_logs` CHANGE `agent` `agent` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `wp_redirection_logs` CHANGE `sent_to` `sent_to` mediumtext COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_redirection_logs` CHANGE `url` `url` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `wp_em_modals` CHANGE `name` `name` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_redirection_items` CHANGE `title` `title` text COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_esign_users` CHANGE `uuid` `uuid` char(36) COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_redirection_items` CHANGE `action_data` `action_data` mediumtext COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_redirection_items` CHANGE `status` `status` enum('enabled','disabled') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'enabled';
ALTER TABLE `wp_redirects` CHANGE `id` `id` mediumint(9) NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_redirection_items` CHANGE `url` `url` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `wp_em_modals` CHANGE `title` `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_redirection_groups` CHANGE `status` `status` enum('enabled','disabled') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'enabled';
ALTER TABLE `wp_redirection_groups` CHANGE `name` `name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `wp_em_modals` CHANGE `content` `content` longtext COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_redirection_404` CHANGE `ip` `ip` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_redirection_404` CHANGE `referrer` `referrer` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_redirection_404` CHANGE `agent` `agent` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_redirection_logs` CHANGE `ip` `ip` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_redirects` CHANGE `count` `count` mediumint(9) NOT NULL DEFAULT '0';
ALTER TABLE `wp_signups` CHANGE `path` `path` varchar(100) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_rg_form_meta` CHANGE `confirmations` `confirmations` longtext COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_em_modal_metas` CHANGE `id` `id` mediumint(9) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_rg_form_view` CHANGE `count` `count` mediumint(8) unsigned NOT NULL DEFAULT '1';
ALTER TABLE `wp_rg_form_view` CHANGE `ip` `ip` char(15) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL;
ALTER TABLE `wp_rg_form_view` CHANGE `form_id` `form_id` mediumint(8) unsigned NOT NULL;
ALTER TABLE `wp_commentmeta` CHANGE `meta_key` `meta_key` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL;
ALTER TABLE `wp_em_modal_metas` CHANGE `modal_id` `modal_id` mediumint(9) unsigned NOT NULL;
ALTER TABLE `wp_em_modal_metas` CHANGE `display` `display` longtext COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_rg_form_meta` CHANGE `notifications` `notifications` longtext COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_yoast_seo_links` CHANGE `url` `url` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL;
ALTER TABLE `wp_em_modals` CHANGE `theme_id` `theme_id` mediumint(9) unsigned NOT NULL DEFAULT '1';
ALTER TABLE `wp_rg_form_meta` CHANGE `entries_grid_meta` `entries_grid_meta` longtext COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_rg_form_meta` CHANGE `display_meta` `display_meta` longtext COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_rg_form_meta` CHANGE `form_id` `form_id` mediumint(8) unsigned NOT NULL;
ALTER TABLE `wp_em_modal_metas` CHANGE `close` `close` longtext COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_yoast_seo_links` CHANGE `type` `type` varchar(8) COLLATE utf8mb4_unicode_520_ci NOT NULL;
ALTER TABLE `wp_rg_form` CHANGE `title` `title` varchar(150) COLLATE utf8mb4_unicode_520_ci NOT NULL;
ALTER TABLE `wp_rg_form` CHANGE `id` `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_em_modals` CHANGE `id` `id` mediumint(9) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_signups` CHANGE `domain` `domain` varchar(200) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_signups` CHANGE `title` `title` longtext COLLATE utf8mb4_unicode_520_ci NOT NULL;
ALTER TABLE `wp_comments` CHANGE `comment_author_IP` `comment_author_IP` varchar(100) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_wfpendingissues` CHANGE `ignoreP` `ignoreP` char(32) NOT NULL;
ALTER TABLE `wp_wfhits` CHANGE `newVisit` `newVisit` tinyint(3) unsigned NOT NULL;
ALTER TABLE `wp_wfhits` CHANGE `isGoogle` `isGoogle` tinyint(4) NOT NULL;
ALTER TABLE `wp_wfhits` CHANGE `jsRun` `jsRun` tinyint(4) DEFAULT '0';
ALTER TABLE `wp_wfhits` CHANGE `IP` `IP` binary(16) DEFAULT NULL;
ALTER TABLE `wp_wfhits` CHANGE `ctime` `ctime` double(17,6) unsigned NOT NULL;
ALTER TABLE `wp_wfhits` CHANGE `attackLogTime` `attackLogTime` double(17,6) unsigned NOT NULL;
ALTER TABLE `wp_ecpt_meta_box_fields` CHANGE `id` `id` mediumint(9) NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_wffilemods` CHANGE `SHAC` `SHAC` binary(32) NOT NULL DEFAULT '\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0';
ALTER TABLE `wp_wfhoover` CHANGE `hostKey` `hostKey` varbinary(124) DEFAULT NULL;
ALTER TABLE `wp_wffilemods` CHANGE `newMD5` `newMD5` binary(16) NOT NULL;
ALTER TABLE `wp_wffilemods` CHANGE `oldMD5` `oldMD5` binary(16) NOT NULL;
ALTER TABLE `wp_wffilemods` CHANGE `knownFile` `knownFile` tinyint(3) unsigned NOT NULL;
ALTER TABLE `wp_wffilemods` CHANGE `filenameMD5` `filenameMD5` binary(16) NOT NULL;
ALTER TABLE `wp_ecpt_meta_box_fields` CHANGE `list_order` `list_order` tinyint(4) NOT NULL;
ALTER TABLE `wp_wffilechanges` CHANGE `md5` `md5` char(32) NOT NULL;
ALTER TABLE `wp_wffilechanges` CHANGE `filenameHash` `filenameHash` char(64) NOT NULL;
ALTER TABLE `wp_ecpt_meta_box_fields` CHANGE `rich_editor` `rich_editor` tinyint(4) NOT NULL;
ALTER TABLE `wp_wfpendingissues` CHANGE `severity` `severity` tinyint(3) unsigned NOT NULL;
ALTER TABLE `wp_wfissues` CHANGE `severity` `severity` tinyint(3) unsigned NOT NULL;
ALTER TABLE `wp_wfcrawlers` CHANGE `patternSig` `patternSig` binary(16) NOT NULL;
ALTER TABLE `wp_wflogins` CHANGE `ctime` `ctime` double(17,6) unsigned NOT NULL;
ALTER TABLE `wp_wfls_settings` CHANGE `autoload` `autoload` enum('no','yes') NOT NULL DEFAULT 'yes';
ALTER TABLE `wp_comments` CHANGE `comment_content` `comment_content` text COLLATE utf8mb4_unicode_520_ci NOT NULL;
ALTER TABLE `wp_wfls_2fa_secrets` CHANGE `mode` `mode` enum('authenticator') NOT NULL DEFAULT 'authenticator';
ALTER TABLE `wp_wfls_2fa_secrets` CHANGE `recovery` `recovery` blob NOT NULL;
ALTER TABLE `wp_wfls_2fa_secrets` CHANGE `secret` `secret` tinyblob NOT NULL;
ALTER TABLE `wp_comments` CHANGE `comment_approved` `comment_approved` varchar(20) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '1';
ALTER TABLE `wp_wflogins` CHANGE `IP` `IP` binary(16) DEFAULT NULL;
ALTER TABLE `wp_wflogins` CHANGE `fail` `fail` tinyint(3) unsigned NOT NULL;
ALTER TABLE `wp_comments` CHANGE `comment_agent` `comment_agent` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_wfissues` CHANGE `ignoreP` `ignoreP` char(32) NOT NULL;
ALTER TABLE `wp_wflocs` CHANGE `countryCode` `countryCode` char(2) DEFAULT '';
ALTER TABLE `wp_wflocs` CHANGE `failed` `failed` tinyint(3) unsigned NOT NULL;
ALTER TABLE `wp_wflocs` CHANGE `IP` `IP` binary(16) NOT NULL DEFAULT '\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0';
ALTER TABLE `wp_comments` CHANGE `comment_author_url` `comment_author_url` varchar(200) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_comments` CHANGE `comment_type` `comment_type` varchar(20) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_wflivetraffichuman` CHANGE `identifier` `identifier` binary(32) NOT NULL DEFAULT '\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0';
ALTER TABLE `wp_wflivetraffichuman` CHANGE `IP` `IP` binary(16) NOT NULL DEFAULT '\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0';
ALTER TABLE `wp_wfissues` CHANGE `ignoreC` `ignoreC` char(32) NOT NULL;
ALTER TABLE `wp_wfcrawlers` CHANGE `status` `status` char(8) NOT NULL;
ALTER TABLE `wp_wfcrawlers` CHANGE `IP` `IP` binary(16) NOT NULL DEFAULT '\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0';
ALTER TABLE `wp_signups` CHANGE `user_login` `user_login` varchar(60) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_term_taxonomy` CHANGE `description` `description` longtext COLLATE utf8mb4_unicode_520_ci NOT NULL;
ALTER TABLE `wp_terms` CHANGE `slug` `slug` varchar(200) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_terms` CHANGE `name` `name` varchar(200) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_ecpt_post_types` CHANGE `author` `author` tinyint(4) NOT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `thumbnail` `thumbnail` tinyint(4) NOT NULL;
ALTER TABLE `wp_termmeta` CHANGE `meta_value` `meta_value` longtext COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_termmeta` CHANGE `meta_key` `meta_key` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `excerpt` `excerpt` tinyint(4) NOT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `fields` `fields` tinyint(4) NOT NULL;
ALTER TABLE `wp_term_taxonomy` CHANGE `taxonomy` `taxonomy` varchar(32) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_wfreversecache` CHANGE `IP` `IP` binary(16) NOT NULL DEFAULT '\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0';
ALTER TABLE `wp_ecpt_post_types` CHANGE `comments` `comments` tinyint(4) NOT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `revisions` `revisions` tinyint(4) NOT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `has_archive` `has_archive` tinyint(4) NOT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `post_formats` `post_formats` tinyint(4) NOT NULL;
ALTER TABLE `wp_wfstatus` CHANGE `ctime` `ctime` double(17,6) unsigned NOT NULL;
ALTER TABLE `wp_signups` CHANGE `meta` `meta` longtext COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_signups` CHANGE `activation_key` `activation_key` varchar(50) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_signups` CHANGE `user_email` `user_email` varchar(100) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_comments` CHANGE `comment_author` `comment_author` tinytext COLLATE utf8mb4_unicode_520_ci NOT NULL;
ALTER TABLE `wp_terms` CHANGE `term_group` `term_group` bigint(10) NOT NULL DEFAULT '0';
ALTER TABLE `wp_ecpt_meta_box_fields` CHANGE `max` `max` tinyint(4) NOT NULL;
ALTER TABLE `wp_users` CHANGE `user_url` `user_url` varchar(100) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_wfconfig` CHANGE `autoload` `autoload` enum('no','yes') NOT NULL DEFAULT 'yes';
ALTER TABLE `wp_wfpendingissues` CHANGE `ignoreC` `ignoreC` char(32) NOT NULL;
ALTER TABLE `wp_wfblocks7` CHANGE `IP` `IP` binary(16) NOT NULL DEFAULT '\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0';
ALTER TABLE `wp_ecpt_meta_boxes` CHANGE `id` `id` mediumint(9) NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_wfblockediplog` CHANGE `IP` `IP` binary(16) NOT NULL DEFAULT '\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0';
ALTER TABLE `wp_comments` CHANGE `comment_author_email` `comment_author_email` varchar(100) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_users` CHANGE `display_name` `display_name` varchar(250) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_users` CHANGE `user_activation_key` `user_activation_key` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_users` CHANGE `user_email` `user_email` varchar(100) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_ecpt_post_types` CHANGE `editor` `editor` tinyint(4) NOT NULL;
ALTER TABLE `wp_users` CHANGE `user_nicename` `user_nicename` varchar(50) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_users` CHANGE `user_pass` `user_pass` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_users` CHANGE `user_login` `user_login` varchar(60) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_ecpt_post_types` CHANGE `id` `id` mediumint(9) NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_ecpt_post_types` CHANGE `hierarchical` `hierarchical` tinyint(4) NOT NULL;
ALTER TABLE `wp_usermeta` CHANGE `meta_value` `meta_value` longtext COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_usermeta` CHANGE `meta_key` `meta_key` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL;
ALTER TABLE `wp_ecpt_post_types` CHANGE `title` `title` tinyint(4) NOT NULL;
ALTER TABLE `wp_redirection_404` CHANGE `url` `url` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_redirection_items` CHANGE `match_type` `match_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `wp_gf_draft_submissions` CHANGE `submission` `submission` longtext COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `wp_hustle_modules` CHANGE `module_name` `module_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `wp_links` CHANGE `link_name` `link_name` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_links` CHANGE `link_url` `link_url` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_hustle_modules_meta` CHANGE `meta_value` `meta_value` longtext COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_hustle_modules_meta` CHANGE `meta_key` `meta_key` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_esign_invitations` CHANGE `invite_hash` `invite_hash` text COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_hustle_modules` CHANGE `test_mode` `test_mode` tinyint(4) DEFAULT '0';
ALTER TABLE `wp_hustle_modules` CHANGE `active` `active` tinyint(4) DEFAULT '1';
ALTER TABLE `wp_hustle_modules` CHANGE `module_type` `module_type` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `wp_esign_invitations` CHANGE `invite_message` `invite_message` longtext COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_links` CHANGE `link_target` `link_target` varchar(25) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_hfcm_scripts` CHANGE `last_modified_by` `last_modified_by` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_hfcm_scripts` CHANGE `created_by` `created_by` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_hfcm_scripts` CHANGE `status` `status` enum('active','inactive') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active';
ALTER TABLE `wp_hfcm_scripts` CHANGE `s_tags` `s_tags` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_hfcm_scripts` CHANGE `s_categories` `s_categories` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_hfcm_scripts` CHANGE `s_custom_posts` `s_custom_posts` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_gf_addon_feed` CHANGE `meta` `meta` longtext COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_hfcm_scripts` CHANGE `ex_posts` `ex_posts` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_links` CHANGE `link_image` `link_image` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_links` CHANGE `link_description` `link_description` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_hfcm_scripts` CHANGE `ex_pages` `ex_pages` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_mail_bank_logs` CHANGE `email_to` `email_to` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_mail_bank_logs` CHANGE `debugging_output` `debugging_output` longtext COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_mail_bank_logs` CHANGE `debug_mode` `debug_mode` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_mail_bank_logs` CHANGE `sender_email` `sender_email` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_mail_bank_logs` CHANGE `sender_name` `sender_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_mail_bank_logs` CHANGE `content` `content` longtext COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_mail_bank_logs` CHANGE `subject` `subject` longtext COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_gf_draft_submissions` CHANGE `source_url` `source_url` longtext COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `wp_mail_bank_logs` CHANGE `cc` `cc` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_gf_addon_feed` CHANGE `form_id` `form_id` mediumint(8) unsigned NOT NULL;
ALTER TABLE `wp_links` CHANGE `link_visible` `link_visible` varchar(20) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT 'Y';
ALTER TABLE `wp_esign_documents_signatures` CHANGE `ip_address` `ip_address` varchar(100) COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_mail_bank_email_logs` CHANGE `email_data` `email_data` longtext COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `wp_esign_documents_signatures` CHANGE `signer_type` `signer_type` varchar(55) COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_mail_bank` CHANGE `type` `type` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `wp_esign_documents_signer_field_data` CHANGE `input_fields` `input_fields` longtext COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_links` CHANGE `link_rss` `link_rss` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_gf_addon_feed` CHANGE `feed_order` `feed_order` mediumint(8) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `wp_links` CHANGE `link_notes` `link_notes` mediumtext COLLATE utf8mb4_unicode_520_ci NOT NULL;
ALTER TABLE `wp_links` CHANGE `link_rel` `link_rel` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_hfcm_scripts` CHANGE `s_posts` `s_posts` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_hfcm_scripts` CHANGE `s_pages` `s_pages` varchar(300) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_esign_documents_meta` CHANGE `meta_value` `meta_value` longtext COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_gf_entry` CHANGE `transaction_id` `transaction_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_esign_settings` CHANGE `setting_value` `setting_value` longtext COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_gf_draft_submissions` CHANGE `uuid` `uuid` char(32) COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `wp_gf_draft_submissions` CHANGE `email` `email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_gf_entry_meta` CHANGE `meta_value` `meta_value` longtext COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_gf_entry_meta` CHANGE `meta_key` `meta_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_gf_entry_meta` CHANGE `form_id` `form_id` mediumint(8) unsigned NOT NULL DEFAULT '0';
ALTER TABLE `wp_gf_draft_submissions` CHANGE `form_id` `form_id` mediumint(8) unsigned NOT NULL;
ALTER TABLE `wp_gf_entry` CHANGE `status` `status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active';
ALTER TABLE `wp_gf_entry` CHANGE `payment_method` `payment_method` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_gf_entry_notes` CHANGE `user_name` `user_name` varchar(250) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_gf_entry` CHANGE `payment_status` `payment_status` varchar(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_gf_entry` CHANGE `currency` `currency` varchar(5) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_gf_draft_submissions` CHANGE `ip` `ip` varchar(39) COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `wp_gf_entry` CHANGE `user_agent` `user_agent` varchar(250) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_gf_entry` CHANGE `source_url` `source_url` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_gf_entry` CHANGE `ip` `ip` varchar(39) COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `wp_gf_entry` CHANGE `form_id` `form_id` mediumint(8) unsigned NOT NULL;
ALTER TABLE `wp_esign_signatures` CHANGE `signature_type` `signature_type` varchar(20) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'full';
ALTER TABLE `wp_esign_signatures` CHANGE `signature_hash` `signature_hash` char(64) COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_gf_entry_notes` CHANGE `value` `value` longtext COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_hfcm_scripts` CHANGE `display_on` `display_on` enum('All','s_pages','s_posts','s_categories','s_custom_posts','s_tags','latest_posts','manual') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'All';
ALTER TABLE `wp_gf_addon_feed` CHANGE `addon_slug` `addon_slug` varchar(50) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL;
ALTER TABLE `wp_hfcm_scripts` CHANGE `location` `location` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `wp_hfcm_scripts` CHANGE `device_type` `device_type` enum('mobile','desktop','both') COLLATE utf8mb4_unicode_ci DEFAULT 'both';
ALTER TABLE `wp_hfcm_scripts` CHANGE `snippet` `snippet` text COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_hfcm_scripts` CHANGE `name` `name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_esign_invitations` CHANGE `sender_ip` `sender_ip` varchar(100) COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_gf_form_view` CHANGE `count` `count` mediumint(8) unsigned NOT NULL DEFAULT '1';
ALTER TABLE `wp_gf_form_view` CHANGE `ip` `ip` char(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_gf_form_view` CHANGE `form_id` `form_id` mediumint(8) unsigned NOT NULL;
ALTER TABLE `wp_gf_form_meta` CHANGE `notifications` `notifications` longtext COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_gf_entry_notes` CHANGE `note_type` `note_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_gf_form_meta` CHANGE `confirmations` `confirmations` longtext COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_gf_form_meta` CHANGE `entries_grid_meta` `entries_grid_meta` longtext COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_gf_form_meta` CHANGE `display_meta` `display_meta` longtext COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_gf_form_meta` CHANGE `form_id` `form_id` mediumint(8) unsigned NOT NULL;
ALTER TABLE `wp_gf_form` CHANGE `title` `title` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `wp_gf_form` CHANGE `id` `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_esign_settings` CHANGE `setting_name` `setting_name` varchar(55) COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_gf_addon_feed` CHANGE `event_type` `event_type` varchar(20) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL;
ALTER TABLE `wp_gf_entry_notes` CHANGE `sub_type` `sub_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_mail_bank_logs` CHANGE `status` `status` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_mail_bank_logs` CHANGE `bcc` `bcc` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL;
ALTER TABLE `wp_esign_documents` CHANGE `document_title` `document_title` varchar(200) COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_esign_document_users` CHANGE `company_name` `company_name` varchar(64) COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_em_theme_metas` CHANGE `id` `id` mediumint(9) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_ontrix_members` CHANGE `validation_code` `validation_code` varchar(8) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL;
ALTER TABLE `wp_esign_documents` CHANGE `document_uri` `document_uri` text COLLATE utf8_unicode_ci;
ALTER TABLE `wp_posts` CHANGE `post_content` `post_content` longtext COLLATE utf8mb4_unicode_520_ci NOT NULL;
ALTER TABLE `wp_esign_documents` CHANGE `document_checksum` `document_checksum` text COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_esign_documents` CHANGE `document_status` `document_status` varchar(24) COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_esign_documents` CHANGE `document_type` `document_type` enum('stand_alone','normal','esig_template','esig-gravity') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'normal';
ALTER TABLE `wp_ontrix_projectapplications` CHANGE `admin_log` `admin_log` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL;
ALTER TABLE `wp_esign_users` CHANGE `last_name` `last_name` varchar(65) COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_esign_users` CHANGE `first_name` `first_name` varchar(45) COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_esign_users` CHANGE `user_title` `user_title` varchar(55) COLLATE utf8_unicode_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_esign_documents` CHANGE `document_content` `document_content` longtext COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_esign_users` CHANGE `user_email` `user_email` varchar(100) COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_ontrix_questionsets` CHANGE `active` `active` tinyint(11) NOT NULL DEFAULT '1';
ALTER TABLE `wp_esign_document_users` CHANGE `signer_email` `signer_email` varchar(64) COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_posts` CHANGE `post_title` `post_title` text COLLATE utf8mb4_unicode_520_ci NOT NULL;
ALTER TABLE `wp_options` CHANGE `option_name` `option_name` varchar(191) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_postmeta` CHANGE `meta_value` `meta_value` longtext COLLATE utf8mb4_unicode_520_ci;
ALTER TABLE `wp_postmeta` CHANGE `meta_key` `meta_key` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL;
ALTER TABLE `wp_em_theme_metas` CHANGE `overlay` `overlay` longtext COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_em_theme_metas` CHANGE `container` `container` longtext COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_options` CHANGE `autoload` `autoload` varchar(20) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT 'yes';
ALTER TABLE `wp_options` CHANGE `option_value` `option_value` longtext COLLATE utf8mb4_unicode_520_ci NOT NULL;
ALTER TABLE `wp_em_theme_metas` CHANGE `close` `close` longtext COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_esign_document_users` CHANGE `signer_name` `signer_name` varchar(64) COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_em_theme_metas` CHANGE `title` `title` longtext COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_em_theme_metas` CHANGE `content` `content` longtext COLLATE utf8mb4_unicode_ci;
ALTER TABLE `wp_em_themes` CHANGE `id` `id` mediumint(9) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_ontrix_smsstatus_old` CHANGE `id` `id` bigint(11) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_ontrix_smsstatus` CHANGE `id` `id` bigint(11) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_em_themes` CHANGE `name` `name` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_ontrix_members` CHANGE `sex` `sex` tinyint(1) DEFAULT '2';
ALTER TABLE `wp_ontrix_members` CHANGE `admin_note` `admin_note` text CHARACTER SET utf8 COLLATE utf8_bin;
ALTER TABLE `wp_posts` CHANGE `post_excerpt` `post_excerpt` text COLLATE utf8mb4_unicode_520_ci NOT NULL;
ALTER TABLE `wp_esign_documents_fields_data` CHANGE `value` `value` longtext COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_ontrix_bulkemails_email` CHANGE `id` `id` bigint(11) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_posts` CHANGE `post_password` `post_password` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_posts` CHANGE `post_name` `post_name` varchar(200) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_esign_documents_fields_data` CHANGE `field_id` `field_id` varchar(100) COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_posts` CHANGE `to_ping` `to_ping` text COLLATE utf8mb4_unicode_520_ci NOT NULL;
ALTER TABLE `wp_posts` CHANGE `pinged` `pinged` text COLLATE utf8mb4_unicode_520_ci NOT NULL;
ALTER TABLE `wp_posts` CHANGE `post_content_filtered` `post_content_filtered` longtext COLLATE utf8mb4_unicode_520_ci NOT NULL;
ALTER TABLE `wp_esign_documents` CHANGE `ip_address` `ip_address` varchar(100) COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_posts` CHANGE `guid` `guid` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_posts` CHANGE `post_type` `post_type` varchar(20) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT 'post';
ALTER TABLE `wp_posts` CHANGE `post_mime_type` `post_mime_type` varchar(100) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '';
ALTER TABLE `wp_ontrix_admin` CHANGE `last_login` `last_login` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE `wp_mail_bank_meta` CHANGE `meta_value` `meta_value` longtext COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `wp_mail_bank_meta` CHANGE `meta_key` `meta_key` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL;
ALTER TABLE `wp_esign_documents_meta` CHANGE `meta_key` `meta_key` varchar(255) COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_posts` CHANGE `ping_status` `ping_status` varchar(20) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT 'open';
ALTER TABLE `wp_ontrix_bulkemails_members` CHANGE `messageid` `messageid` bigint(11) NOT NULL;
ALTER TABLE `wp_em_theme_metas` CHANGE `theme_id` `theme_id` mediumint(9) unsigned NOT NULL;
ALTER TABLE `wp_esign_documents_events` CHANGE `event` `event` varchar(20) COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_ontrix_memberprojectica` CHANGE `i_agree` `i_agree` tinyint(4) NOT NULL DEFAULT '1';
ALTER TABLE `wp_ontrix_memberprojectica` CHANGE `icaid` `icaid` bigint(11) NOT NULL DEFAULT '0';
ALTER TABLE `wp_ontrix_memberprojectica` CHANGE `projectid` `projectid` bigint(11) NOT NULL DEFAULT '0';
ALTER TABLE `wp_ontrix_memberprojectica` CHANGE `memberid` `memberid` bigint(11) unsigned NOT NULL;
ALTER TABLE `wp_posts` CHANGE `post_status` `post_status` varchar(20) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT 'publish';
ALTER TABLE `wp_esign_signatures` CHANGE `signature_data` `signature_data` longtext COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_ontrix_ica` CHANGE `ica_id` `ica_id` bigint(11) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_esign_documents_events` CHANGE `event_data` `event_data` varchar(256) COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_posts` CHANGE `comment_status` `comment_status` varchar(20) COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT 'open';
ALTER TABLE `wp_esign_signatures` CHANGE `signature_salt` `signature_salt` char(40) COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_gf_addon_feed` CHANGE `id` `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT;
ALTER TABLE `wp_esign_documents_events` CHANGE `ip_address` `ip_address` varchar(100) COLLATE utf8_unicode_ci NOT NULL;
ALTER TABLE `wp_wflogins` DROP INDEX `IP`;
ALTER TABLE `wp_wfhits` DROP INDEX `IP`;
ALTER TABLE `wp_gf_entry` DROP INDEX `form_id_2`;
ALTER TABLE `wp_comments` DROP INDEX `comment_approved`;
ALTER TABLE `wp_wfhoover` DROP INDEX `hostKey`;
ALTER TABLE `wp_yoast_seo_links` DROP INDEX `post_id`;
ALTER TABLE `wp_wfhits` DROP INDEX `ctime`;
ALTER TABLE `wp_gf_addon_feed` DROP INDEX `addon_slug`;
ALTER TABLE `wp_redirection_items` DROP INDEX `group_id`;
ALTER TABLE `wp_term_taxonomy` DROP INDEX `term_id`;
ALTER TABLE `wp_redirection_items` DROP INDEX `group_id_2`;
ALTER TABLE `wp_ontrix_projectapplications` DROP INDEX `projectid_2`;
ALTER TABLE `wp_ontrix_admin_old` DROP INDEX `email`;
ALTER TABLE `wp_rg_lead_detail` DROP INDEX `lead_id_2`;
ALTER TABLE `wp_posts` DROP INDEX `post_type`;
ALTER TABLE `wp_wfstatus` DROP INDEX `type`;
ALTER TABLE `wp_rg_lead_meta` DROP INDEX `form_id`;
ALTER TABLE `wp_signups` DROP INDEX `user_login`;
ALTER TABLE `wp_ontrix_projectapplications` DROP INDEX `projectid`;
ALTER TABLE `wp_users` DROP INDEX `user_login`;
ALTER TABLE `wp_ontrix_projectapplications` DROP INDEX `projectid_3`;
ALTER TABLE `wp_wfstatus` DROP INDEX `ctime`;
ALTER TABLE `wp_ontrix_projectapplications` DROP INDEX `projectid_4`;
ALTER TABLE `wp_rg_lead_notes` DROP INDEX `lead_id_2`;
ALTER TABLE `wp_gf_entry_notes` DROP INDEX `entry_id_2`;
ALTER TABLE `wp_signups` DROP INDEX `domain`;
ALTER TABLE `wp_rg_lead_meta` DROP INDEX `meta_key`;
ALTER TABLE `wp_rg_lead_meta` ADD KEY `meta_key` (`meta_key`(191));
ALTER TABLE `wp_commentmeta` DROP INDEX `meta_key`;
ALTER TABLE `wp_commentmeta` ADD KEY `meta_key` (`meta_key`(191));
ALTER TABLE `wp_redirection_404` DROP INDEX `url`;
ALTER TABLE `wp_redirection_404` ADD KEY `url` (`url`(191));
ALTER TABLE `wp_redirection_404` DROP INDEX `referrer`;
ALTER TABLE `wp_redirection_404` ADD KEY `referrer` (`referrer`(191));
ALTER TABLE `wp_posts` DROP INDEX `post_name`;
ALTER TABLE `wp_posts` ADD KEY `post_name` (`post_name`(191));
ALTER TABLE `wp_termmeta` DROP INDEX `meta_key`;
ALTER TABLE `wp_termmeta` ADD KEY `meta_key` (`meta_key`(191));
ALTER TABLE `wp_esign_documents_events` DROP INDEX `event_data`;
ALTER TABLE `wp_esign_documents_events` ADD KEY `event_data` (`event_data`(255));
ALTER TABLE `wp_terms` DROP INDEX `slug`;
ALTER TABLE `wp_terms` ADD KEY `slug` (`slug`(191));
ALTER TABLE `wp_terms` DROP INDEX `name`;
ALTER TABLE `wp_terms` ADD KEY `name` (`name`(191));
ALTER TABLE `wp_comments` DROP INDEX `comment_author_email`;
ALTER TABLE `wp_comments` ADD KEY `comment_author_email` (`comment_author_email`(10));
ALTER TABLE `wp_gf_entry_meta` DROP INDEX `meta_key`;
ALTER TABLE `wp_gf_entry_meta` ADD KEY `meta_key` (`meta_key`(191));
ALTER TABLE `wp_usermeta` DROP INDEX `meta_key`;
ALTER TABLE `wp_usermeta` ADD KEY `meta_key` (`meta_key`(191));
ALTER TABLE `wp_postmeta` DROP INDEX `meta_key`;
ALTER TABLE `wp_postmeta` ADD KEY `meta_key` (`meta_key`(191));
ALTER TABLE `wp_wfstatus` ADD KEY `k1` (`ctime`);
ALTER TABLE `wp_gf_addon_feed` ADD KEY `addon_form` (`addon_slug`,`form_id`);
ALTER TABLE `wp_yoast_seo_links` ADD KEY `link_direction` (`post_id`,`type`);
ALTER TABLE `wp_wfstatus` ADD KEY `k2` (`type`);
ALTER TABLE `wp_posts` ADD KEY `type_status_date` (`post_type`,`post_status`,`post_date`,`ID`);
ALTER TABLE `wp_wflogins` ADD KEY `k1` (`IP`,`fail`);
ALTER TABLE `wp_ontrix_admin` ADD UNIQUE KEY `NewIndex1` (`adminid`);
ALTER TABLE `wp_redirection_items` ADD KEY `url` (`url`(191));
ALTER TABLE `wp_redirection_items` ADD KEY `group_idpos` (`group_id`,`position`);
ALTER TABLE `wp_redirection_items` ADD KEY `group` (`group_id`);
ALTER TABLE `wp_ontrix_projectapplications` ADD KEY `IDX_PROJ_CONF` (`projectid`,`confirmation`);
ALTER TABLE `wp_ontrix_projectapplications` ADD KEY `IDX_PROJ_DEN` (`projectid`,`denied`);
ALTER TABLE `wp_ontrix_projectapplications` ADD KEY `IDX_PROJ_APPR` (`projectid`,`approved`);
ALTER TABLE `wp_esign_documents` ADD KEY `document_checksum` (`document_checksum`(100));
ALTER TABLE `wp_rg_lead_detail` ADD KEY `lead_field_number` (`lead_id`,`field_number`);
ALTER TABLE `wp_rg_lead_detail` ADD KEY `lead_field_value` (`value`(191));
ALTER TABLE `wp_ontrix_admin_old` ADD UNIQUE KEY `NewIndex1` (`email`);
ALTER TABLE `wp_rg_lead_meta` ADD KEY `form_id_meta_key` (`form_id`,`meta_key`(191));
ALTER TABLE `wp_rg_lead_notes` ADD KEY `lead_user_key` (`lead_id`,`user_id`);
ALTER TABLE `wp_gf_entry` ADD KEY `form_id_status` (`form_id`,`status`);
ALTER TABLE `wp_signups` ADD KEY `user_login_email` (`user_login`,`user_email`);
ALTER TABLE `wp_signups` ADD KEY `domain_path` (`domain`(140),`path`(51));
ALTER TABLE `wp_term_taxonomy` ADD UNIQUE KEY `term_id_taxonomy` (`term_id`,`taxonomy`);
ALTER TABLE `wp_users` ADD KEY `user_login_key` (`user_login`);
ALTER TABLE `wp_esign_invitations` ADD KEY `invite_hash` (`invite_hash`(100));
ALTER TABLE `wp_gf_entry_notes` ADD KEY `entry_user_key` (`entry_id`,`user_id`);
ALTER TABLE `wp_wfhits` ADD KEY `k1` (`ctime`);
ALTER TABLE `wp_wfhits` ADD KEY `k2` (`IP`,`ctime`);
ALTER TABLE `wp_wfhoover` ADD KEY `k2` (`hostKey`);
ALTER TABLE `wp_gf_entry_meta` ADD KEY `meta_value` (`meta_value`(191));
ALTER TABLE `wp_comments` ADD KEY `comment_approved_date_gmt` (`comment_approved`,`comment_date_gmt`);
ALTER TABLE `wp_ontrix_projectapplications` ADD KEY `IDX_PROJ_ID` (`projectid`);
"""
